### ISSUE TITLE
Update README during release

### ISSUE THREAD

**Issue by dkundel** [twilio-labs/plugin-webhook#3]
Right now when the `npm run version` is executed by the GitHub Actions flow on merge to `main` it does not commit the actual `README.md` changes generated by `oclif-dev readme`. This is primarily a problem since the `README.md` file contains links that make use of the version tag meaning those will be outdated.

**Comment by meeraj257** [comment]
@dkundel - i will work on this bug.  Pls assign to me.

**Comment by dkundel** [comment]
Thanks for the PR @meeraj257 ! This has been merged in #6
